import type { ReactNode } from "react";

const HEADER = "<header class=\"site-header\">\n  <div class=\"container header-inner\">\n    <a class=\"brand\" href=\"/\" aria-label=\"Vizier op Scherp \u2014 naar de homepage\">\n      <svg width=\"34\" height=\"34\" viewBox=\"0 0 100 100\" aria-hidden=\"true\"><rect x=\"8\" y=\"8\" width=\"84\" height=\"84\" rx=\"10\" fill=\"#1F3D3B\"></rect><path d=\"M50 26 L74 50 L50 74 L26 50 Z\" fill=\"none\" stroke=\"#E8714A\" stroke-width=\"6\" stroke-linejoin=\"miter\"></path><rect x=\"44\" y=\"44\" width=\"12\" height=\"12\" fill=\"#F2C879\" transform=\"rotate(45 50 50)\"></rect></svg>\n      <span>Vizier op Scherp</span>\n    </a>\n    <nav class=\"main-nav\" aria-label=\"Hoofdnavigatie\">\n      <a href=\"/voor-werkgevers\">Voor werkgevers &amp; HR</a>\n      <a href=\"/coaching-voor-mij\">Coaching voor mij</a>\n      <a href=\"/uwv-traject\">UWV-traject</a>\n      <a href=\"/coaches\">Onze coaches</a>\n      <a href=\"/over-ons\">Over ons</a>\n      <a class=\"nav-cta\" href=\"/kennismaken\">Kennismaken</a>\n    </nav>\n  </div>\n</header>";
const FOOTER = "<footer class=\"site-footer\">\n  <div class=\"container\">\n    <div class=\"footer-grid\">\n      <div>\n        <a class=\"footer-brand\" href=\"/\" aria-label=\"Vizier op Scherp \u2014 naar de homepage\">\n          <svg width=\"30\" height=\"30\" viewBox=\"0 0 100 100\" aria-hidden=\"true\"><rect x=\"8\" y=\"8\" width=\"84\" height=\"84\" rx=\"10\" fill=\"#F5EFE3\"></rect><path d=\"M50 26 L74 50 L50 74 L26 50 Z\" fill=\"none\" stroke=\"#1F3D3B\" stroke-width=\"6\" stroke-linejoin=\"miter\"></path><rect x=\"44\" y=\"44\" width=\"12\" height=\"12\" fill=\"#E8714A\" transform=\"rotate(45 50 50)\"></rect></svg>\n          <span>Vizier op Scherp</span>\n        </a>\n        <p>Regionaal netwerk voor loopbaancoaching, voor werkgevers en hun medewerkers in Amsterdam, Haarlem en omgeving. Persoonlijk, professioneel en gericht op concrete stappen in werk.</p>\n      </div>\n      <div>\n        <h2>Doelgroepen</h2>\n        <a href=\"/voor-werkgevers\">Voor werkgevers &amp; HR</a>\n        <a href=\"/coaching-voor-mij\">Coaching voor mij</a>\n        <a href=\"/uwv-traject\">UWV-traject</a>\n        <a href=\"/leiderschap\">Leiderschap &amp; talentontwikkeling</a>\n      </div>\n      <div>\n        <h2>Bureau</h2>\n        <a href=\"/coaches\">Onze coaches</a>\n        <a href=\"/over-ons\">Over ons</a>\n        <a href=\"/kennismaken\">Kennismaken</a>\n        <a class=\"gold-link\" href=\"/inzichten\">Inzichten</a>\n      </div>\n      <div>\n        <h2>Contact</h2>\n        <address><strong>Haarlem</strong>Klein Heiligland 84, 2011 EJ Haarlem</address>\n        <address><strong>Amsterdam</strong>IJsbaanpad 9, 1076 CV Amsterdam</address>\n        <a href=\"mailto:hallo@vizieropscherp.nl\">hallo@vizieropscherp.nl</a>\n        <a href=\"tel:+31202146466\">020 214 64 66</a>\n      </div>\n    </div>\n    <div class=\"footer-bottom\">\n      <span>\u00a9 2016 - 2026 Vizier op Scherp \u00b7 KVK 81088701 \u00b7 BTW NL003529887B45</span>\n      <a href=\"/privacyverklaring\">Privacyverklaring</a>\n      <a href=\"/algemene-voorwaarden\">Algemene voorwaarden</a>\n      <a href=\"https://www.linkedin.com/company/10002759/\" rel=\"noopener\">LinkedIn</a>\n    </div>\n  </div>\n</footer>";

export default function LegalLayout({ children }: { children: ReactNode }) {
  return (
    <>
      <div dangerouslySetInnerHTML={{ __html: HEADER }} />
      <main>
        <section className="section" style={{ background: "var(--paper)" }}>
          <div className="legal-wrap">{children}</div>
        </section>
      </main>
      <div dangerouslySetInnerHTML={{ __html: FOOTER }} />
    </>
  );
}
