/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VoorWerkgeversRouteImport } from './routes/voor-werkgevers'
import { Route as UwvTrajectRouteImport } from './routes/uwv-traject'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PrivacyverklaringRouteImport } from './routes/privacyverklaring'
import { Route as OverOnsRouteImport } from './routes/over-ons'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LeiderschapRouteImport } from './routes/leiderschap'
import { Route as KennismakenRouteImport } from './routes/kennismaken'
import { Route as InzichtenRouteImport } from './routes/inzichten'
import { Route as CoachingVoorMijRouteImport } from './routes/coaching-voor-mij'
import { Route as CoachesRouteImport } from './routes/coaches'
import { Route as AlgemeneVoorwaardenRouteImport } from './routes/algemene-voorwaarden'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InzichtenIndexRouteImport } from './routes/inzichten.index'
import { Route as InzichtenVierBasisbehoeftenInWerkRouteImport } from './routes/inzichten.vier-basisbehoeften-in-werk'
import { Route as InzichtenVastzittenInEenGoedeBaanRouteImport } from './routes/inzichten.vastzitten-in-een-goede-baan'
import { Route as InzichtenVanWervenNaarBehoudenRouteImport } from './routes/inzichten.van-werven-naar-behouden'
import { Route as InzichtenStartersBehoudenRouteImport } from './routes/inzichten.starters-behouden'
import { Route as InzichtenSolliciterenEnArbeidsmarktRouteImport } from './routes/inzichten.solliciteren-en-arbeidsmarkt'
import { Route as InzichtenSkillsgerichtWervenRouteImport } from './routes/inzichten.skillsgericht-werven'
import { Route as InzichtenRichtingVindenInJeLoopbaanRouteImport } from './routes/inzichten.richting-vinden-in-je-loopbaan'
import { Route as InzichtenPersoonlijkeEffectiviteitRouteImport } from './routes/inzichten.persoonlijke-effectiviteit'
import { Route as InzichtenPassieTerugvindenInJeWerkRouteImport } from './routes/inzichten.passie-terugvinden-in-je-werk'
import { Route as InzichtenOutplacementOfLoopbaancoachingRouteImport } from './routes/inzichten.outplacement-of-loopbaancoaching'
import { Route as InzichtenMentaleVermoeidheidEnEigenRegieRouteImport } from './routes/inzichten.mentale-vermoeidheid-en-eigen-regie'
import { Route as InzichtenLoopbaanswitchNaJe40eRouteImport } from './routes/inzichten.loopbaanswitch-na-je-40e'
import { Route as InzichtenLoopbaangesprekMetMedewerkerRouteImport } from './routes/inzichten.loopbaangesprek-met-medewerker'
import { Route as InzichtenKostenVanEenVerkeerdeMatchRouteImport } from './routes/inzichten.kosten-van-een-verkeerde-match'
import { Route as InzichtenJobCraftingRouteImport } from './routes/inzichten.job-crafting'
import { Route as InzichtenJeEersteBaanRouteImport } from './routes/inzichten.je-eerste-baan'
import { Route as InzichtenImpostersyndroomTwijfelAlsKrachtRouteImport } from './routes/inzichten.impostersyndroom-twijfel-als-kracht'
import { Route as InzichtenHetTegenbodRouteImport } from './routes/inzichten.het-tegenbod'
import { Route as InzichtenGoedeLoopbaancoachKiezenRouteImport } from './routes/inzichten.goede-loopbaancoach-kiezen'
import { Route as InzichtenGeneratiesOpDeWerkvloerRouteImport } from './routes/inzichten.generaties-op-de-werkvloer'
import { Route as InzichtenErvarenTalentAlsKansRouteImport } from './routes/inzichten.ervaren-talent-als-kans'
import { Route as InzichtenEnergieEnMotivatieInWerkRouteImport } from './routes/inzichten.energie-en-motivatie-in-werk'
import { Route as InzichtenDuurzameInzetbaarheidWerkgeverRouteImport } from './routes/inzichten.duurzame-inzetbaarheid-werkgever'
import { Route as InzichtenDuurzaamInzetbaarBlijvenRouteImport } from './routes/inzichten.duurzaam-inzetbaar-blijven'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicSubmitFormRouteImport } from './routes/api/public/submit-form'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const VoorWerkgeversRoute = VoorWerkgeversRouteImport.update({
  id: '/voor-werkgevers',
  path: '/voor-werkgevers',
  getParentRoute: () => rootRouteImport,
} as any)
const UwvTrajectRoute = UwvTrajectRouteImport.update({
  id: '/uwv-traject',
  path: '/uwv-traject',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyverklaringRoute = PrivacyverklaringRouteImport.update({
  id: '/privacyverklaring',
  path: '/privacyverklaring',
  getParentRoute: () => rootRouteImport,
} as any)
const OverOnsRoute = OverOnsRouteImport.update({
  id: '/over-ons',
  path: '/over-ons',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LeiderschapRoute = LeiderschapRouteImport.update({
  id: '/leiderschap',
  path: '/leiderschap',
  getParentRoute: () => rootRouteImport,
} as any)
const KennismakenRoute = KennismakenRouteImport.update({
  id: '/kennismaken',
  path: '/kennismaken',
  getParentRoute: () => rootRouteImport,
} as any)
const InzichtenRoute = InzichtenRouteImport.update({
  id: '/inzichten',
  path: '/inzichten',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachingVoorMijRoute = CoachingVoorMijRouteImport.update({
  id: '/coaching-voor-mij',
  path: '/coaching-voor-mij',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachesRoute = CoachesRouteImport.update({
  id: '/coaches',
  path: '/coaches',
  getParentRoute: () => rootRouteImport,
} as any)
const AlgemeneVoorwaardenRoute = AlgemeneVoorwaardenRouteImport.update({
  id: '/algemene-voorwaarden',
  path: '/algemene-voorwaarden',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InzichtenIndexRoute = InzichtenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InzichtenRoute,
} as any)
const InzichtenVierBasisbehoeftenInWerkRoute =
  InzichtenVierBasisbehoeftenInWerkRouteImport.update({
    id: '/vier-basisbehoeften-in-werk',
    path: '/vier-basisbehoeften-in-werk',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenVastzittenInEenGoedeBaanRoute =
  InzichtenVastzittenInEenGoedeBaanRouteImport.update({
    id: '/vastzitten-in-een-goede-baan',
    path: '/vastzitten-in-een-goede-baan',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenVanWervenNaarBehoudenRoute =
  InzichtenVanWervenNaarBehoudenRouteImport.update({
    id: '/van-werven-naar-behouden',
    path: '/van-werven-naar-behouden',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenStartersBehoudenRoute =
  InzichtenStartersBehoudenRouteImport.update({
    id: '/starters-behouden',
    path: '/starters-behouden',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenSolliciterenEnArbeidsmarktRoute =
  InzichtenSolliciterenEnArbeidsmarktRouteImport.update({
    id: '/solliciteren-en-arbeidsmarkt',
    path: '/solliciteren-en-arbeidsmarkt',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenSkillsgerichtWervenRoute =
  InzichtenSkillsgerichtWervenRouteImport.update({
    id: '/skillsgericht-werven',
    path: '/skillsgericht-werven',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenRichtingVindenInJeLoopbaanRoute =
  InzichtenRichtingVindenInJeLoopbaanRouteImport.update({
    id: '/richting-vinden-in-je-loopbaan',
    path: '/richting-vinden-in-je-loopbaan',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenPersoonlijkeEffectiviteitRoute =
  InzichtenPersoonlijkeEffectiviteitRouteImport.update({
    id: '/persoonlijke-effectiviteit',
    path: '/persoonlijke-effectiviteit',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenPassieTerugvindenInJeWerkRoute =
  InzichtenPassieTerugvindenInJeWerkRouteImport.update({
    id: '/passie-terugvinden-in-je-werk',
    path: '/passie-terugvinden-in-je-werk',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenOutplacementOfLoopbaancoachingRoute =
  InzichtenOutplacementOfLoopbaancoachingRouteImport.update({
    id: '/outplacement-of-loopbaancoaching',
    path: '/outplacement-of-loopbaancoaching',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenMentaleVermoeidheidEnEigenRegieRoute =
  InzichtenMentaleVermoeidheidEnEigenRegieRouteImport.update({
    id: '/mentale-vermoeidheid-en-eigen-regie',
    path: '/mentale-vermoeidheid-en-eigen-regie',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenLoopbaanswitchNaJe40eRoute =
  InzichtenLoopbaanswitchNaJe40eRouteImport.update({
    id: '/loopbaanswitch-na-je-40e',
    path: '/loopbaanswitch-na-je-40e',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenLoopbaangesprekMetMedewerkerRoute =
  InzichtenLoopbaangesprekMetMedewerkerRouteImport.update({
    id: '/loopbaangesprek-met-medewerker',
    path: '/loopbaangesprek-met-medewerker',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenKostenVanEenVerkeerdeMatchRoute =
  InzichtenKostenVanEenVerkeerdeMatchRouteImport.update({
    id: '/kosten-van-een-verkeerde-match',
    path: '/kosten-van-een-verkeerde-match',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenJobCraftingRoute = InzichtenJobCraftingRouteImport.update({
  id: '/job-crafting',
  path: '/job-crafting',
  getParentRoute: () => InzichtenRoute,
} as any)
const InzichtenJeEersteBaanRoute = InzichtenJeEersteBaanRouteImport.update({
  id: '/je-eerste-baan',
  path: '/je-eerste-baan',
  getParentRoute: () => InzichtenRoute,
} as any)
const InzichtenImpostersyndroomTwijfelAlsKrachtRoute =
  InzichtenImpostersyndroomTwijfelAlsKrachtRouteImport.update({
    id: '/impostersyndroom-twijfel-als-kracht',
    path: '/impostersyndroom-twijfel-als-kracht',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenHetTegenbodRoute = InzichtenHetTegenbodRouteImport.update({
  id: '/het-tegenbod',
  path: '/het-tegenbod',
  getParentRoute: () => InzichtenRoute,
} as any)
const InzichtenGoedeLoopbaancoachKiezenRoute =
  InzichtenGoedeLoopbaancoachKiezenRouteImport.update({
    id: '/goede-loopbaancoach-kiezen',
    path: '/goede-loopbaancoach-kiezen',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenGeneratiesOpDeWerkvloerRoute =
  InzichtenGeneratiesOpDeWerkvloerRouteImport.update({
    id: '/generaties-op-de-werkvloer',
    path: '/generaties-op-de-werkvloer',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenErvarenTalentAlsKansRoute =
  InzichtenErvarenTalentAlsKansRouteImport.update({
    id: '/ervaren-talent-als-kans',
    path: '/ervaren-talent-als-kans',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenEnergieEnMotivatieInWerkRoute =
  InzichtenEnergieEnMotivatieInWerkRouteImport.update({
    id: '/energie-en-motivatie-in-werk',
    path: '/energie-en-motivatie-in-werk',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenDuurzameInzetbaarheidWerkgeverRoute =
  InzichtenDuurzameInzetbaarheidWerkgeverRouteImport.update({
    id: '/duurzame-inzetbaarheid-werkgever',
    path: '/duurzame-inzetbaarheid-werkgever',
    getParentRoute: () => InzichtenRoute,
  } as any)
const InzichtenDuurzaamInzetbaarBlijvenRoute =
  InzichtenDuurzaamInzetbaarBlijvenRouteImport.update({
    id: '/duurzaam-inzetbaar-blijven',
    path: '/duurzaam-inzetbaar-blijven',
    getParentRoute: () => InzichtenRoute,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSubmitFormRoute = ApiPublicSubmitFormRouteImport.update({
  id: '/api/public/submit-form',
  path: '/api/public/submit-form',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/coaches': typeof CoachesRoute
  '/coaching-voor-mij': typeof CoachingVoorMijRoute
  '/inzichten': typeof InzichtenRouteWithChildren
  '/kennismaken': typeof KennismakenRoute
  '/leiderschap': typeof LeiderschapRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uwv-traject': typeof UwvTrajectRoute
  '/voor-werkgevers': typeof VoorWerkgeversRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/inzichten/duurzaam-inzetbaar-blijven': typeof InzichtenDuurzaamInzetbaarBlijvenRoute
  '/inzichten/duurzame-inzetbaarheid-werkgever': typeof InzichtenDuurzameInzetbaarheidWerkgeverRoute
  '/inzichten/energie-en-motivatie-in-werk': typeof InzichtenEnergieEnMotivatieInWerkRoute
  '/inzichten/ervaren-talent-als-kans': typeof InzichtenErvarenTalentAlsKansRoute
  '/inzichten/generaties-op-de-werkvloer': typeof InzichtenGeneratiesOpDeWerkvloerRoute
  '/inzichten/goede-loopbaancoach-kiezen': typeof InzichtenGoedeLoopbaancoachKiezenRoute
  '/inzichten/het-tegenbod': typeof InzichtenHetTegenbodRoute
  '/inzichten/impostersyndroom-twijfel-als-kracht': typeof InzichtenImpostersyndroomTwijfelAlsKrachtRoute
  '/inzichten/je-eerste-baan': typeof InzichtenJeEersteBaanRoute
  '/inzichten/job-crafting': typeof InzichtenJobCraftingRoute
  '/inzichten/kosten-van-een-verkeerde-match': typeof InzichtenKostenVanEenVerkeerdeMatchRoute
  '/inzichten/loopbaangesprek-met-medewerker': typeof InzichtenLoopbaangesprekMetMedewerkerRoute
  '/inzichten/loopbaanswitch-na-je-40e': typeof InzichtenLoopbaanswitchNaJe40eRoute
  '/inzichten/mentale-vermoeidheid-en-eigen-regie': typeof InzichtenMentaleVermoeidheidEnEigenRegieRoute
  '/inzichten/outplacement-of-loopbaancoaching': typeof InzichtenOutplacementOfLoopbaancoachingRoute
  '/inzichten/passie-terugvinden-in-je-werk': typeof InzichtenPassieTerugvindenInJeWerkRoute
  '/inzichten/persoonlijke-effectiviteit': typeof InzichtenPersoonlijkeEffectiviteitRoute
  '/inzichten/richting-vinden-in-je-loopbaan': typeof InzichtenRichtingVindenInJeLoopbaanRoute
  '/inzichten/skillsgericht-werven': typeof InzichtenSkillsgerichtWervenRoute
  '/inzichten/solliciteren-en-arbeidsmarkt': typeof InzichtenSolliciterenEnArbeidsmarktRoute
  '/inzichten/starters-behouden': typeof InzichtenStartersBehoudenRoute
  '/inzichten/van-werven-naar-behouden': typeof InzichtenVanWervenNaarBehoudenRoute
  '/inzichten/vastzitten-in-een-goede-baan': typeof InzichtenVastzittenInEenGoedeBaanRoute
  '/inzichten/vier-basisbehoeften-in-werk': typeof InzichtenVierBasisbehoeftenInWerkRoute
  '/inzichten/': typeof InzichtenIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/coaches': typeof CoachesRoute
  '/coaching-voor-mij': typeof CoachingVoorMijRoute
  '/kennismaken': typeof KennismakenRoute
  '/leiderschap': typeof LeiderschapRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uwv-traject': typeof UwvTrajectRoute
  '/voor-werkgevers': typeof VoorWerkgeversRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/inzichten/duurzaam-inzetbaar-blijven': typeof InzichtenDuurzaamInzetbaarBlijvenRoute
  '/inzichten/duurzame-inzetbaarheid-werkgever': typeof InzichtenDuurzameInzetbaarheidWerkgeverRoute
  '/inzichten/energie-en-motivatie-in-werk': typeof InzichtenEnergieEnMotivatieInWerkRoute
  '/inzichten/ervaren-talent-als-kans': typeof InzichtenErvarenTalentAlsKansRoute
  '/inzichten/generaties-op-de-werkvloer': typeof InzichtenGeneratiesOpDeWerkvloerRoute
  '/inzichten/goede-loopbaancoach-kiezen': typeof InzichtenGoedeLoopbaancoachKiezenRoute
  '/inzichten/het-tegenbod': typeof InzichtenHetTegenbodRoute
  '/inzichten/impostersyndroom-twijfel-als-kracht': typeof InzichtenImpostersyndroomTwijfelAlsKrachtRoute
  '/inzichten/je-eerste-baan': typeof InzichtenJeEersteBaanRoute
  '/inzichten/job-crafting': typeof InzichtenJobCraftingRoute
  '/inzichten/kosten-van-een-verkeerde-match': typeof InzichtenKostenVanEenVerkeerdeMatchRoute
  '/inzichten/loopbaangesprek-met-medewerker': typeof InzichtenLoopbaangesprekMetMedewerkerRoute
  '/inzichten/loopbaanswitch-na-je-40e': typeof InzichtenLoopbaanswitchNaJe40eRoute
  '/inzichten/mentale-vermoeidheid-en-eigen-regie': typeof InzichtenMentaleVermoeidheidEnEigenRegieRoute
  '/inzichten/outplacement-of-loopbaancoaching': typeof InzichtenOutplacementOfLoopbaancoachingRoute
  '/inzichten/passie-terugvinden-in-je-werk': typeof InzichtenPassieTerugvindenInJeWerkRoute
  '/inzichten/persoonlijke-effectiviteit': typeof InzichtenPersoonlijkeEffectiviteitRoute
  '/inzichten/richting-vinden-in-je-loopbaan': typeof InzichtenRichtingVindenInJeLoopbaanRoute
  '/inzichten/skillsgericht-werven': typeof InzichtenSkillsgerichtWervenRoute
  '/inzichten/solliciteren-en-arbeidsmarkt': typeof InzichtenSolliciterenEnArbeidsmarktRoute
  '/inzichten/starters-behouden': typeof InzichtenStartersBehoudenRoute
  '/inzichten/van-werven-naar-behouden': typeof InzichtenVanWervenNaarBehoudenRoute
  '/inzichten/vastzitten-in-een-goede-baan': typeof InzichtenVastzittenInEenGoedeBaanRoute
  '/inzichten/vier-basisbehoeften-in-werk': typeof InzichtenVierBasisbehoeftenInWerkRoute
  '/inzichten': typeof InzichtenIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/algemene-voorwaarden': typeof AlgemeneVoorwaardenRoute
  '/coaches': typeof CoachesRoute
  '/coaching-voor-mij': typeof CoachingVoorMijRoute
  '/inzichten': typeof InzichtenRouteWithChildren
  '/kennismaken': typeof KennismakenRoute
  '/leiderschap': typeof LeiderschapRoute
  '/mcp': typeof McpRoute
  '/over-ons': typeof OverOnsRoute
  '/privacyverklaring': typeof PrivacyverklaringRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/uwv-traject': typeof UwvTrajectRoute
  '/voor-werkgevers': typeof VoorWerkgeversRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/inzichten/duurzaam-inzetbaar-blijven': typeof InzichtenDuurzaamInzetbaarBlijvenRoute
  '/inzichten/duurzame-inzetbaarheid-werkgever': typeof InzichtenDuurzameInzetbaarheidWerkgeverRoute
  '/inzichten/energie-en-motivatie-in-werk': typeof InzichtenEnergieEnMotivatieInWerkRoute
  '/inzichten/ervaren-talent-als-kans': typeof InzichtenErvarenTalentAlsKansRoute
  '/inzichten/generaties-op-de-werkvloer': typeof InzichtenGeneratiesOpDeWerkvloerRoute
  '/inzichten/goede-loopbaancoach-kiezen': typeof InzichtenGoedeLoopbaancoachKiezenRoute
  '/inzichten/het-tegenbod': typeof InzichtenHetTegenbodRoute
  '/inzichten/impostersyndroom-twijfel-als-kracht': typeof InzichtenImpostersyndroomTwijfelAlsKrachtRoute
  '/inzichten/je-eerste-baan': typeof InzichtenJeEersteBaanRoute
  '/inzichten/job-crafting': typeof InzichtenJobCraftingRoute
  '/inzichten/kosten-van-een-verkeerde-match': typeof InzichtenKostenVanEenVerkeerdeMatchRoute
  '/inzichten/loopbaangesprek-met-medewerker': typeof InzichtenLoopbaangesprekMetMedewerkerRoute
  '/inzichten/loopbaanswitch-na-je-40e': typeof InzichtenLoopbaanswitchNaJe40eRoute
  '/inzichten/mentale-vermoeidheid-en-eigen-regie': typeof InzichtenMentaleVermoeidheidEnEigenRegieRoute
  '/inzichten/outplacement-of-loopbaancoaching': typeof InzichtenOutplacementOfLoopbaancoachingRoute
  '/inzichten/passie-terugvinden-in-je-werk': typeof InzichtenPassieTerugvindenInJeWerkRoute
  '/inzichten/persoonlijke-effectiviteit': typeof InzichtenPersoonlijkeEffectiviteitRoute
  '/inzichten/richting-vinden-in-je-loopbaan': typeof InzichtenRichtingVindenInJeLoopbaanRoute
  '/inzichten/skillsgericht-werven': typeof InzichtenSkillsgerichtWervenRoute
  '/inzichten/solliciteren-en-arbeidsmarkt': typeof InzichtenSolliciterenEnArbeidsmarktRoute
  '/inzichten/starters-behouden': typeof InzichtenStartersBehoudenRoute
  '/inzichten/van-werven-naar-behouden': typeof InzichtenVanWervenNaarBehoudenRoute
  '/inzichten/vastzitten-in-een-goede-baan': typeof InzichtenVastzittenInEenGoedeBaanRoute
  '/inzichten/vier-basisbehoeften-in-werk': typeof InzichtenVierBasisbehoeftenInWerkRoute
  '/inzichten/': typeof InzichtenIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/submit-form': typeof ApiPublicSubmitFormRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/algemene-voorwaarden'
    | '/coaches'
    | '/coaching-voor-mij'
    | '/inzichten'
    | '/kennismaken'
    | '/leiderschap'
    | '/mcp'
    | '/over-ons'
    | '/privacyverklaring'
    | '/sitemap.xml'
    | '/uwv-traject'
    | '/voor-werkgevers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/inzichten/duurzaam-inzetbaar-blijven'
    | '/inzichten/duurzame-inzetbaarheid-werkgever'
    | '/inzichten/energie-en-motivatie-in-werk'
    | '/inzichten/ervaren-talent-als-kans'
    | '/inzichten/generaties-op-de-werkvloer'
    | '/inzichten/goede-loopbaancoach-kiezen'
    | '/inzichten/het-tegenbod'
    | '/inzichten/impostersyndroom-twijfel-als-kracht'
    | '/inzichten/je-eerste-baan'
    | '/inzichten/job-crafting'
    | '/inzichten/kosten-van-een-verkeerde-match'
    | '/inzichten/loopbaangesprek-met-medewerker'
    | '/inzichten/loopbaanswitch-na-je-40e'
    | '/inzichten/mentale-vermoeidheid-en-eigen-regie'
    | '/inzichten/outplacement-of-loopbaancoaching'
    | '/inzichten/passie-terugvinden-in-je-werk'
    | '/inzichten/persoonlijke-effectiviteit'
    | '/inzichten/richting-vinden-in-je-loopbaan'
    | '/inzichten/skillsgericht-werven'
    | '/inzichten/solliciteren-en-arbeidsmarkt'
    | '/inzichten/starters-behouden'
    | '/inzichten/van-werven-naar-behouden'
    | '/inzichten/vastzitten-in-een-goede-baan'
    | '/inzichten/vier-basisbehoeften-in-werk'
    | '/inzichten/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/submit-form'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/algemene-voorwaarden'
    | '/coaches'
    | '/coaching-voor-mij'
    | '/kennismaken'
    | '/leiderschap'
    | '/mcp'
    | '/over-ons'
    | '/privacyverklaring'
    | '/sitemap.xml'
    | '/uwv-traject'
    | '/voor-werkgevers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/inzichten/duurzaam-inzetbaar-blijven'
    | '/inzichten/duurzame-inzetbaarheid-werkgever'
    | '/inzichten/energie-en-motivatie-in-werk'
    | '/inzichten/ervaren-talent-als-kans'
    | '/inzichten/generaties-op-de-werkvloer'
    | '/inzichten/goede-loopbaancoach-kiezen'
    | '/inzichten/het-tegenbod'
    | '/inzichten/impostersyndroom-twijfel-als-kracht'
    | '/inzichten/je-eerste-baan'
    | '/inzichten/job-crafting'
    | '/inzichten/kosten-van-een-verkeerde-match'
    | '/inzichten/loopbaangesprek-met-medewerker'
    | '/inzichten/loopbaanswitch-na-je-40e'
    | '/inzichten/mentale-vermoeidheid-en-eigen-regie'
    | '/inzichten/outplacement-of-loopbaancoaching'
    | '/inzichten/passie-terugvinden-in-je-werk'
    | '/inzichten/persoonlijke-effectiviteit'
    | '/inzichten/richting-vinden-in-je-loopbaan'
    | '/inzichten/skillsgericht-werven'
    | '/inzichten/solliciteren-en-arbeidsmarkt'
    | '/inzichten/starters-behouden'
    | '/inzichten/van-werven-naar-behouden'
    | '/inzichten/vastzitten-in-een-goede-baan'
    | '/inzichten/vier-basisbehoeften-in-werk'
    | '/inzichten'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/submit-form'
  id:
    | '__root__'
    | '/'
    | '/algemene-voorwaarden'
    | '/coaches'
    | '/coaching-voor-mij'
    | '/inzichten'
    | '/kennismaken'
    | '/leiderschap'
    | '/mcp'
    | '/over-ons'
    | '/privacyverklaring'
    | '/sitemap.xml'
    | '/uwv-traject'
    | '/voor-werkgevers'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/inzichten/duurzaam-inzetbaar-blijven'
    | '/inzichten/duurzame-inzetbaarheid-werkgever'
    | '/inzichten/energie-en-motivatie-in-werk'
    | '/inzichten/ervaren-talent-als-kans'
    | '/inzichten/generaties-op-de-werkvloer'
    | '/inzichten/goede-loopbaancoach-kiezen'
    | '/inzichten/het-tegenbod'
    | '/inzichten/impostersyndroom-twijfel-als-kracht'
    | '/inzichten/je-eerste-baan'
    | '/inzichten/job-crafting'
    | '/inzichten/kosten-van-een-verkeerde-match'
    | '/inzichten/loopbaangesprek-met-medewerker'
    | '/inzichten/loopbaanswitch-na-je-40e'
    | '/inzichten/mentale-vermoeidheid-en-eigen-regie'
    | '/inzichten/outplacement-of-loopbaancoaching'
    | '/inzichten/passie-terugvinden-in-je-werk'
    | '/inzichten/persoonlijke-effectiviteit'
    | '/inzichten/richting-vinden-in-je-loopbaan'
    | '/inzichten/skillsgericht-werven'
    | '/inzichten/solliciteren-en-arbeidsmarkt'
    | '/inzichten/starters-behouden'
    | '/inzichten/van-werven-naar-behouden'
    | '/inzichten/vastzitten-in-een-goede-baan'
    | '/inzichten/vier-basisbehoeften-in-werk'
    | '/inzichten/'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/submit-form'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlgemeneVoorwaardenRoute: typeof AlgemeneVoorwaardenRoute
  CoachesRoute: typeof CoachesRoute
  CoachingVoorMijRoute: typeof CoachingVoorMijRoute
  InzichtenRoute: typeof InzichtenRouteWithChildren
  KennismakenRoute: typeof KennismakenRoute
  LeiderschapRoute: typeof LeiderschapRoute
  McpRoute: typeof McpRoute
  OverOnsRoute: typeof OverOnsRoute
  PrivacyverklaringRoute: typeof PrivacyverklaringRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  UwvTrajectRoute: typeof UwvTrajectRoute
  VoorWerkgeversRoute: typeof VoorWerkgeversRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicSubmitFormRoute: typeof ApiPublicSubmitFormRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/voor-werkgevers': {
      id: '/voor-werkgevers'
      path: '/voor-werkgevers'
      fullPath: '/voor-werkgevers'
      preLoaderRoute: typeof VoorWerkgeversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uwv-traject': {
      id: '/uwv-traject'
      path: '/uwv-traject'
      fullPath: '/uwv-traject'
      preLoaderRoute: typeof UwvTrajectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacyverklaring': {
      id: '/privacyverklaring'
      path: '/privacyverklaring'
      fullPath: '/privacyverklaring'
      preLoaderRoute: typeof PrivacyverklaringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/over-ons': {
      id: '/over-ons'
      path: '/over-ons'
      fullPath: '/over-ons'
      preLoaderRoute: typeof OverOnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leiderschap': {
      id: '/leiderschap'
      path: '/leiderschap'
      fullPath: '/leiderschap'
      preLoaderRoute: typeof LeiderschapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kennismaken': {
      id: '/kennismaken'
      path: '/kennismaken'
      fullPath: '/kennismaken'
      preLoaderRoute: typeof KennismakenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inzichten': {
      id: '/inzichten'
      path: '/inzichten'
      fullPath: '/inzichten'
      preLoaderRoute: typeof InzichtenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaching-voor-mij': {
      id: '/coaching-voor-mij'
      path: '/coaching-voor-mij'
      fullPath: '/coaching-voor-mij'
      preLoaderRoute: typeof CoachingVoorMijRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coaches': {
      id: '/coaches'
      path: '/coaches'
      fullPath: '/coaches'
      preLoaderRoute: typeof CoachesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/algemene-voorwaarden': {
      id: '/algemene-voorwaarden'
      path: '/algemene-voorwaarden'
      fullPath: '/algemene-voorwaarden'
      preLoaderRoute: typeof AlgemeneVoorwaardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inzichten/': {
      id: '/inzichten/'
      path: '/'
      fullPath: '/inzichten/'
      preLoaderRoute: typeof InzichtenIndexRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/vier-basisbehoeften-in-werk': {
      id: '/inzichten/vier-basisbehoeften-in-werk'
      path: '/vier-basisbehoeften-in-werk'
      fullPath: '/inzichten/vier-basisbehoeften-in-werk'
      preLoaderRoute: typeof InzichtenVierBasisbehoeftenInWerkRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/vastzitten-in-een-goede-baan': {
      id: '/inzichten/vastzitten-in-een-goede-baan'
      path: '/vastzitten-in-een-goede-baan'
      fullPath: '/inzichten/vastzitten-in-een-goede-baan'
      preLoaderRoute: typeof InzichtenVastzittenInEenGoedeBaanRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/van-werven-naar-behouden': {
      id: '/inzichten/van-werven-naar-behouden'
      path: '/van-werven-naar-behouden'
      fullPath: '/inzichten/van-werven-naar-behouden'
      preLoaderRoute: typeof InzichtenVanWervenNaarBehoudenRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/starters-behouden': {
      id: '/inzichten/starters-behouden'
      path: '/starters-behouden'
      fullPath: '/inzichten/starters-behouden'
      preLoaderRoute: typeof InzichtenStartersBehoudenRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/solliciteren-en-arbeidsmarkt': {
      id: '/inzichten/solliciteren-en-arbeidsmarkt'
      path: '/solliciteren-en-arbeidsmarkt'
      fullPath: '/inzichten/solliciteren-en-arbeidsmarkt'
      preLoaderRoute: typeof InzichtenSolliciterenEnArbeidsmarktRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/skillsgericht-werven': {
      id: '/inzichten/skillsgericht-werven'
      path: '/skillsgericht-werven'
      fullPath: '/inzichten/skillsgericht-werven'
      preLoaderRoute: typeof InzichtenSkillsgerichtWervenRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/richting-vinden-in-je-loopbaan': {
      id: '/inzichten/richting-vinden-in-je-loopbaan'
      path: '/richting-vinden-in-je-loopbaan'
      fullPath: '/inzichten/richting-vinden-in-je-loopbaan'
      preLoaderRoute: typeof InzichtenRichtingVindenInJeLoopbaanRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/persoonlijke-effectiviteit': {
      id: '/inzichten/persoonlijke-effectiviteit'
      path: '/persoonlijke-effectiviteit'
      fullPath: '/inzichten/persoonlijke-effectiviteit'
      preLoaderRoute: typeof InzichtenPersoonlijkeEffectiviteitRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/passie-terugvinden-in-je-werk': {
      id: '/inzichten/passie-terugvinden-in-je-werk'
      path: '/passie-terugvinden-in-je-werk'
      fullPath: '/inzichten/passie-terugvinden-in-je-werk'
      preLoaderRoute: typeof InzichtenPassieTerugvindenInJeWerkRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/outplacement-of-loopbaancoaching': {
      id: '/inzichten/outplacement-of-loopbaancoaching'
      path: '/outplacement-of-loopbaancoaching'
      fullPath: '/inzichten/outplacement-of-loopbaancoaching'
      preLoaderRoute: typeof InzichtenOutplacementOfLoopbaancoachingRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/mentale-vermoeidheid-en-eigen-regie': {
      id: '/inzichten/mentale-vermoeidheid-en-eigen-regie'
      path: '/mentale-vermoeidheid-en-eigen-regie'
      fullPath: '/inzichten/mentale-vermoeidheid-en-eigen-regie'
      preLoaderRoute: typeof InzichtenMentaleVermoeidheidEnEigenRegieRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/loopbaanswitch-na-je-40e': {
      id: '/inzichten/loopbaanswitch-na-je-40e'
      path: '/loopbaanswitch-na-je-40e'
      fullPath: '/inzichten/loopbaanswitch-na-je-40e'
      preLoaderRoute: typeof InzichtenLoopbaanswitchNaJe40eRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/loopbaangesprek-met-medewerker': {
      id: '/inzichten/loopbaangesprek-met-medewerker'
      path: '/loopbaangesprek-met-medewerker'
      fullPath: '/inzichten/loopbaangesprek-met-medewerker'
      preLoaderRoute: typeof InzichtenLoopbaangesprekMetMedewerkerRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/kosten-van-een-verkeerde-match': {
      id: '/inzichten/kosten-van-een-verkeerde-match'
      path: '/kosten-van-een-verkeerde-match'
      fullPath: '/inzichten/kosten-van-een-verkeerde-match'
      preLoaderRoute: typeof InzichtenKostenVanEenVerkeerdeMatchRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/job-crafting': {
      id: '/inzichten/job-crafting'
      path: '/job-crafting'
      fullPath: '/inzichten/job-crafting'
      preLoaderRoute: typeof InzichtenJobCraftingRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/je-eerste-baan': {
      id: '/inzichten/je-eerste-baan'
      path: '/je-eerste-baan'
      fullPath: '/inzichten/je-eerste-baan'
      preLoaderRoute: typeof InzichtenJeEersteBaanRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/impostersyndroom-twijfel-als-kracht': {
      id: '/inzichten/impostersyndroom-twijfel-als-kracht'
      path: '/impostersyndroom-twijfel-als-kracht'
      fullPath: '/inzichten/impostersyndroom-twijfel-als-kracht'
      preLoaderRoute: typeof InzichtenImpostersyndroomTwijfelAlsKrachtRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/het-tegenbod': {
      id: '/inzichten/het-tegenbod'
      path: '/het-tegenbod'
      fullPath: '/inzichten/het-tegenbod'
      preLoaderRoute: typeof InzichtenHetTegenbodRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/goede-loopbaancoach-kiezen': {
      id: '/inzichten/goede-loopbaancoach-kiezen'
      path: '/goede-loopbaancoach-kiezen'
      fullPath: '/inzichten/goede-loopbaancoach-kiezen'
      preLoaderRoute: typeof InzichtenGoedeLoopbaancoachKiezenRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/generaties-op-de-werkvloer': {
      id: '/inzichten/generaties-op-de-werkvloer'
      path: '/generaties-op-de-werkvloer'
      fullPath: '/inzichten/generaties-op-de-werkvloer'
      preLoaderRoute: typeof InzichtenGeneratiesOpDeWerkvloerRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/ervaren-talent-als-kans': {
      id: '/inzichten/ervaren-talent-als-kans'
      path: '/ervaren-talent-als-kans'
      fullPath: '/inzichten/ervaren-talent-als-kans'
      preLoaderRoute: typeof InzichtenErvarenTalentAlsKansRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/energie-en-motivatie-in-werk': {
      id: '/inzichten/energie-en-motivatie-in-werk'
      path: '/energie-en-motivatie-in-werk'
      fullPath: '/inzichten/energie-en-motivatie-in-werk'
      preLoaderRoute: typeof InzichtenEnergieEnMotivatieInWerkRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/duurzame-inzetbaarheid-werkgever': {
      id: '/inzichten/duurzame-inzetbaarheid-werkgever'
      path: '/duurzame-inzetbaarheid-werkgever'
      fullPath: '/inzichten/duurzame-inzetbaarheid-werkgever'
      preLoaderRoute: typeof InzichtenDuurzameInzetbaarheidWerkgeverRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/inzichten/duurzaam-inzetbaar-blijven': {
      id: '/inzichten/duurzaam-inzetbaar-blijven'
      path: '/duurzaam-inzetbaar-blijven'
      fullPath: '/inzichten/duurzaam-inzetbaar-blijven'
      preLoaderRoute: typeof InzichtenDuurzaamInzetbaarBlijvenRouteImport
      parentRoute: typeof InzichtenRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/submit-form': {
      id: '/api/public/submit-form'
      path: '/api/public/submit-form'
      fullPath: '/api/public/submit-form'
      preLoaderRoute: typeof ApiPublicSubmitFormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InzichtenRouteChildren {
  InzichtenDuurzaamInzetbaarBlijvenRoute: typeof InzichtenDuurzaamInzetbaarBlijvenRoute
  InzichtenDuurzameInzetbaarheidWerkgeverRoute: typeof InzichtenDuurzameInzetbaarheidWerkgeverRoute
  InzichtenEnergieEnMotivatieInWerkRoute: typeof InzichtenEnergieEnMotivatieInWerkRoute
  InzichtenErvarenTalentAlsKansRoute: typeof InzichtenErvarenTalentAlsKansRoute
  InzichtenGeneratiesOpDeWerkvloerRoute: typeof InzichtenGeneratiesOpDeWerkvloerRoute
  InzichtenGoedeLoopbaancoachKiezenRoute: typeof InzichtenGoedeLoopbaancoachKiezenRoute
  InzichtenHetTegenbodRoute: typeof InzichtenHetTegenbodRoute
  InzichtenImpostersyndroomTwijfelAlsKrachtRoute: typeof InzichtenImpostersyndroomTwijfelAlsKrachtRoute
  InzichtenJeEersteBaanRoute: typeof InzichtenJeEersteBaanRoute
  InzichtenJobCraftingRoute: typeof InzichtenJobCraftingRoute
  InzichtenKostenVanEenVerkeerdeMatchRoute: typeof InzichtenKostenVanEenVerkeerdeMatchRoute
  InzichtenLoopbaangesprekMetMedewerkerRoute: typeof InzichtenLoopbaangesprekMetMedewerkerRoute
  InzichtenLoopbaanswitchNaJe40eRoute: typeof InzichtenLoopbaanswitchNaJe40eRoute
  InzichtenMentaleVermoeidheidEnEigenRegieRoute: typeof InzichtenMentaleVermoeidheidEnEigenRegieRoute
  InzichtenOutplacementOfLoopbaancoachingRoute: typeof InzichtenOutplacementOfLoopbaancoachingRoute
  InzichtenPassieTerugvindenInJeWerkRoute: typeof InzichtenPassieTerugvindenInJeWerkRoute
  InzichtenPersoonlijkeEffectiviteitRoute: typeof InzichtenPersoonlijkeEffectiviteitRoute
  InzichtenRichtingVindenInJeLoopbaanRoute: typeof InzichtenRichtingVindenInJeLoopbaanRoute
  InzichtenSkillsgerichtWervenRoute: typeof InzichtenSkillsgerichtWervenRoute
  InzichtenSolliciterenEnArbeidsmarktRoute: typeof InzichtenSolliciterenEnArbeidsmarktRoute
  InzichtenStartersBehoudenRoute: typeof InzichtenStartersBehoudenRoute
  InzichtenVanWervenNaarBehoudenRoute: typeof InzichtenVanWervenNaarBehoudenRoute
  InzichtenVastzittenInEenGoedeBaanRoute: typeof InzichtenVastzittenInEenGoedeBaanRoute
  InzichtenVierBasisbehoeftenInWerkRoute: typeof InzichtenVierBasisbehoeftenInWerkRoute
  InzichtenIndexRoute: typeof InzichtenIndexRoute
}

const InzichtenRouteChildren: InzichtenRouteChildren = {
  InzichtenDuurzaamInzetbaarBlijvenRoute:
    InzichtenDuurzaamInzetbaarBlijvenRoute,
  InzichtenDuurzameInzetbaarheidWerkgeverRoute:
    InzichtenDuurzameInzetbaarheidWerkgeverRoute,
  InzichtenEnergieEnMotivatieInWerkRoute:
    InzichtenEnergieEnMotivatieInWerkRoute,
  InzichtenErvarenTalentAlsKansRoute: InzichtenErvarenTalentAlsKansRoute,
  InzichtenGeneratiesOpDeWerkvloerRoute: InzichtenGeneratiesOpDeWerkvloerRoute,
  InzichtenGoedeLoopbaancoachKiezenRoute:
    InzichtenGoedeLoopbaancoachKiezenRoute,
  InzichtenHetTegenbodRoute: InzichtenHetTegenbodRoute,
  InzichtenImpostersyndroomTwijfelAlsKrachtRoute:
    InzichtenImpostersyndroomTwijfelAlsKrachtRoute,
  InzichtenJeEersteBaanRoute: InzichtenJeEersteBaanRoute,
  InzichtenJobCraftingRoute: InzichtenJobCraftingRoute,
  InzichtenKostenVanEenVerkeerdeMatchRoute:
    InzichtenKostenVanEenVerkeerdeMatchRoute,
  InzichtenLoopbaangesprekMetMedewerkerRoute:
    InzichtenLoopbaangesprekMetMedewerkerRoute,
  InzichtenLoopbaanswitchNaJe40eRoute: InzichtenLoopbaanswitchNaJe40eRoute,
  InzichtenMentaleVermoeidheidEnEigenRegieRoute:
    InzichtenMentaleVermoeidheidEnEigenRegieRoute,
  InzichtenOutplacementOfLoopbaancoachingRoute:
    InzichtenOutplacementOfLoopbaancoachingRoute,
  InzichtenPassieTerugvindenInJeWerkRoute:
    InzichtenPassieTerugvindenInJeWerkRoute,
  InzichtenPersoonlijkeEffectiviteitRoute:
    InzichtenPersoonlijkeEffectiviteitRoute,
  InzichtenRichtingVindenInJeLoopbaanRoute:
    InzichtenRichtingVindenInJeLoopbaanRoute,
  InzichtenSkillsgerichtWervenRoute: InzichtenSkillsgerichtWervenRoute,
  InzichtenSolliciterenEnArbeidsmarktRoute:
    InzichtenSolliciterenEnArbeidsmarktRoute,
  InzichtenStartersBehoudenRoute: InzichtenStartersBehoudenRoute,
  InzichtenVanWervenNaarBehoudenRoute: InzichtenVanWervenNaarBehoudenRoute,
  InzichtenVastzittenInEenGoedeBaanRoute:
    InzichtenVastzittenInEenGoedeBaanRoute,
  InzichtenVierBasisbehoeftenInWerkRoute:
    InzichtenVierBasisbehoeftenInWerkRoute,
  InzichtenIndexRoute: InzichtenIndexRoute,
}

const InzichtenRouteWithChildren = InzichtenRoute._addFileChildren(
  InzichtenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlgemeneVoorwaardenRoute: AlgemeneVoorwaardenRoute,
  CoachesRoute: CoachesRoute,
  CoachingVoorMijRoute: CoachingVoorMijRoute,
  InzichtenRoute: InzichtenRouteWithChildren,
  KennismakenRoute: KennismakenRoute,
  LeiderschapRoute: LeiderschapRoute,
  McpRoute: McpRoute,
  OverOnsRoute: OverOnsRoute,
  PrivacyverklaringRoute: PrivacyverklaringRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  UwvTrajectRoute: UwvTrajectRoute,
  VoorWerkgeversRoute: VoorWerkgeversRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicSubmitFormRoute: ApiPublicSubmitFormRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
